#!/bin/bash
# Get latest git tag
latest_tag=$(git describe --tags --abbrev=0)
version_from_tag=$(echo "$latest_tag" | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+')

# Get the version from package.json
version=$(jq -r '.version' package.json)

echo "Latest tag: $latest_tag"
echo "Version from tag: $version_from_tag"
echo "Version from package.json: $version"

# Check if the version from the tag and package.json are the same
if [ "$version" != "$version_from_tag" ]; then
  echo "Version in package.json and tag are not the same"
  exit 1
fi
