name: Continuous Integration

on:
  push:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          yarn install --frozen-lockfile --prefer-offline

      - name: Run Lint
        run: |
          yarn lint --max-warnings=0

      - name: Run tests
        uses: willcaul/jest-github-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "yarn test"
